// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: droneService.proto

package dronev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Movement_Enum int32

const (
	Movement_takeoff  Movement_Enum = 0
	Movement_up       Movement_Enum = 1
	Movement_down     Movement_Enum = 2
	Movement_right    Movement_Enum = 3
	Movement_left     Movement_Enum = 4
	Movement_forward  Movement_Enum = 5
	Movement_backward Movement_Enum = 6
	Movement_figure8  Movement_Enum = 7
	Movement_circle   Movement_Enum = 8
	Movement_zigzag   Movement_Enum = 9
	Movement_landing  Movement_Enum = 10
)

// Enum value maps for Movement_Enum.
var (
	Movement_Enum_name = map[int32]string{
		0:  "takeoff",
		1:  "up",
		2:  "down",
		3:  "right",
		4:  "left",
		5:  "forward",
		6:  "backward",
		7:  "figure8",
		8:  "circle",
		9:  "zigzag",
		10: "landing",
	}
	Movement_Enum_value = map[string]int32{
		"takeoff":  0,
		"up":       1,
		"down":     2,
		"right":    3,
		"left":     4,
		"forward":  5,
		"backward": 6,
		"figure8":  7,
		"circle":   8,
		"zigzag":   9,
		"landing":  10,
	}
)

func (x Movement_Enum) Enum() *Movement_Enum {
	p := new(Movement_Enum)
	*p = x
	return p
}

func (x Movement_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Movement_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_droneService_proto_enumTypes[0].Descriptor()
}

func (Movement_Enum) Type() protoreflect.EnumType {
	return &file_droneService_proto_enumTypes[0]
}

func (x Movement_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Movement_Enum.Descriptor instead.
func (Movement_Enum) EnumDescriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{3, 0}
}

type MovementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Movement Movement_Enum `protobuf:"varint,1,opt,name=movement,proto3,enum=drone.Movement_Enum" json:"movement,omitempty"`
}

func (x *MovementRequest) Reset() {
	*x = MovementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droneService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovementRequest) ProtoMessage() {}

func (x *MovementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_droneService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovementRequest.ProtoReflect.Descriptor instead.
func (*MovementRequest) Descriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{0}
}

func (x *MovementRequest) GetMovement() Movement_Enum {
	if x != nil {
		return x.Movement
	}
	return Movement_takeoff
}

type GetCoordinateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCoordinateRequest) Reset() {
	*x = GetCoordinateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droneService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoordinateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinateRequest) ProtoMessage() {}

func (x *GetCoordinateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_droneService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinateRequest.ProtoReflect.Descriptor instead.
func (*GetCoordinateRequest) Descriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{1}
}

type GetCoordinateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinate *Coordinate            `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	Time       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *GetCoordinateResponse) Reset() {
	*x = GetCoordinateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droneService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoordinateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoordinateResponse) ProtoMessage() {}

func (x *GetCoordinateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_droneService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoordinateResponse.ProtoReflect.Descriptor instead.
func (*GetCoordinateResponse) Descriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoordinateResponse) GetCoordinate() *Coordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *GetCoordinateResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Movement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Movement) Reset() {
	*x = Movement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droneService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_droneService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{3}
}

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude  float32 `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_droneService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_droneService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_droneService_proto_rawDescGZIP(), []int{4}
}

func (x *Coordinate) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinate) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

var File_droneService_proto protoreflect.FileDescriptor

var file_droneService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0f,
	0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x30, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x7a, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x74,
	0x61, 0x6b, 0x65, 0x6f, 0x66, 0x66, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x75, 0x70, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x10, 0x04, 0x12,
	0x0b, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08,
	0x62, 0x61, 0x63, 0x6b, 0x77, 0x61, 0x72, 0x64, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x38, 0x10, 0x07, 0x12, 0x0a, 0x0a, 0x06, 0x63, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x7a, 0x69, 0x67, 0x7a, 0x61, 0x67, 0x10, 0x09, 0x12,
	0x0b, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x0a, 0x22, 0x62, 0x0a, 0x0a,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x32, 0x9c, 0x01, 0x0a, 0x0c, 0x44, 0x72, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x12, 0x1b, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a,
	0x08, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x64, 0x72, 0x6f, 0x6e,
	0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x64, 0x72, 0x6f, 0x6e, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_droneService_proto_rawDescOnce sync.Once
	file_droneService_proto_rawDescData = file_droneService_proto_rawDesc
)

func file_droneService_proto_rawDescGZIP() []byte {
	file_droneService_proto_rawDescOnce.Do(func() {
		file_droneService_proto_rawDescData = protoimpl.X.CompressGZIP(file_droneService_proto_rawDescData)
	})
	return file_droneService_proto_rawDescData
}

var file_droneService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_droneService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_droneService_proto_goTypes = []interface{}{
	(Movement_Enum)(0),            // 0: drone.Movement.Enum
	(*MovementRequest)(nil),       // 1: drone.MovementRequest
	(*GetCoordinateRequest)(nil),  // 2: drone.GetCoordinateRequest
	(*GetCoordinateResponse)(nil), // 3: drone.GetCoordinateResponse
	(*Movement)(nil),              // 4: drone.Movement
	(*Coordinate)(nil),            // 5: drone.Coordinate
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_droneService_proto_depIdxs = []int32{
	0, // 0: drone.MovementRequest.movement:type_name -> drone.Movement.Enum
	5, // 1: drone.GetCoordinateResponse.coordinate:type_name -> drone.Coordinate
	6, // 2: drone.GetCoordinateResponse.time:type_name -> google.protobuf.Timestamp
	2, // 3: drone.DroneService.GetCoordinate:input_type -> drone.GetCoordinateRequest
	1, // 4: drone.DroneService.Movement:input_type -> drone.MovementRequest
	3, // 5: drone.DroneService.GetCoordinate:output_type -> drone.GetCoordinateResponse
	3, // 6: drone.DroneService.Movement:output_type -> drone.GetCoordinateResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_droneService_proto_init() }
func file_droneService_proto_init() {
	if File_droneService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_droneService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droneService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoordinateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droneService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoordinateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droneService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Movement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_droneService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_droneService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_droneService_proto_goTypes,
		DependencyIndexes: file_droneService_proto_depIdxs,
		EnumInfos:         file_droneService_proto_enumTypes,
		MessageInfos:      file_droneService_proto_msgTypes,
	}.Build()
	File_droneService_proto = out.File
	file_droneService_proto_rawDesc = nil
	file_droneService_proto_goTypes = nil
	file_droneService_proto_depIdxs = nil
}
